[package]
name = "opengate-terminal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tokio-util.workspace = true
portable-pty.workspace = true
crossterm.workspace = true
futures.workspace = true
opengate-protocol.workspace = true
