[package]
name = "opengate-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
opengate-core.workspace = true
opengate-protocol.workspace = true
tokio-util.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
windows-service.workspace = true
windows-sys.workspace = true
